### PR TITLE
add merchant-web for merchant interface

### PR DESCRIPTION
**Pull request by Geno117**
Rough look.
Any major missing elements?

### CODE REVIEW

**Comment by KHvic** [comment]
It would be nice if you could upload a screenshot!

**Comment by Geno117** [comment]
Screenshot from 2020-03-05 23-10-50

Screenshot from 2020-03-05 23-07-02


Obviously a work in progress. However, i just wanted to show you that I am working on.

I'm more concerned about getting all the components connected now.

**Comment by zshanhui** [comment]
Hey, just noticed this PR right now!

Thanks, this is just what we need! Just a few things on the components to make sure we have everything.

- Can we make the most urgent order first on top? (So the order would be reversed from what you have?) I imagined normally people scanned from top down right?
- So anything under 5 minutes, perhaps we can highlight it red. The others we can leave neutral color. What do you think?
- One tricky thing here, not sure if you've implemented yet, is that the timer is always running right? The calculation is going to take 2 inputs: interval: Integer`15|30|45|60`, and the confirmation time: Timestamp `2020-03-02 21:27:03.942668+08` and calculates the time remaining `TimeToPickup`, so that would be `confirmation_time` + `pickup_in`, and then we order by this result. We can probably do this in the API before returning the results to client. The client just needs to make sure that the order is always maintained from most urgent to farthest away.
- It seems more concise to just say "Pick up in `MM:SS`"
- Let's save the merchant authentication for another task and PR laster.

- And lastly is seems that you are not using the React.js project. Really recommended to use our existing architecture and routing using Express and React.js. It'll be hard to integrate later otherwise. Here is the file I've set up for the Merchant dashboard routes: https://github.com/adrienshen/facebook-bizchat-hackathon/blob/master/src/client/js/pages/MerchantRoutes.js

Perhaps we can work on this PR together as well as it has fairly complex components.

**Comment by zshanhui** [comment]
Hmm, I think I'll merge this in for now and move what you have implemented over to React.

**Pull request merged**
