### PR TITLE
Receipts

### PR DESCRIPTION
**Pull request by johnbenedictyan**
Issue #8 

- Added the receipt model
- Added the add receipt function to generate a new receipt
- Modified the existing order model to include a function that return's its id to check that the order 
  exist.
- Added the webview for the merchant

### CODE REVIEW

**Comment by zshanhui** [comment]
Code looks generally good! Since it's a hackathon, we're going to prioritize moving fast over code quality. There's seems to be a conflict with master branch though.

Also, do you mind posting screenshot of UI based work such as the receipt so we can get a basic overview of the UI this PR implements?

**Comment by johnbenedictyan** [comment]
receipt_ui

This is what the receipt would look like. It's pretty basic at the moment.
I have also resolved the merge conflicts.

**Comment by johnbenedictyan** [comment]
> receipt_ui
> 
> This is what the receipt would look like. It's pretty basic at the moment.
> I have also resolved the merge conflicts.

The price of the entire receipt does not match the sum of the individual line items for now.

**Comment by zshanhui** [comment]
Thanks for the work on the Receipt. Looks like we have all the basic elements already. I'm just going to put a Doordash receipt for reference to see what we still need.

Screenshot 2020-03-05 12 39 14

- Can we style it in a row with ` Quantity | Name | Price `?
- Perhaps we can remove the description as that's not really necessary on the receipt, right?
- Let's calculate the subtotal and taxes after the LineItems section. So the subtotal would be the sum of all the LineItems of a orderId times its' quantity. I just pushed the model for LineItems earlier. Perhaps you can implement something like: `Order.calculateSubtotal -> Integer in cents`, then use that to create the Receipts row.
- Can we format the date in human friendly form like `15th Feb 2020`, or whatever is most intuitive in SG?
- Can we include the Merchant shop name somewhere on top before the LineItems, Eg. Doordash

Nice to haves:

- Would be nice to greet customers like: "Thank you for your order, <Customer>"
- We might want a placeholder for the platform name or logo later

**Comment by zshanhui** [comment]
I fixed the crash, if anything else let me know. Still working on the styling right?

**Comment by johnbenedictyan** [comment]
Yes, I will update the styling and create another PR.

**Pull request merged**
