### PR TITLE
add merchant-ui components

### PR DESCRIPTION
**Pull request by Geno117**
I'll work on the ui portion a bit more. what are the lower hanging fruits for the components or are ther any good material on setting up and using opstgres with knew and getting queries. Perhaps then I could step in a bit more.

### CODE REVIEW

**Comment by zshanhui** [comment]
Hey, thanks for the ongoing work with Components. It's great that you're learning React. Will try to implement what you have into the Dashboard I'm working on now.

I have a task for you that will help you learn React.js and it's various parts:
- Build a `<CountDownTimer />` component.

Example screenshot of basic timer: https://www.dropbox.com/s/fq9fr57k09yewyk/Screenshot%202020-03-08%2014.14.50.png?dl=0

Here's what we want <CountDownTimer /> to do:

- pass it one prop: `pickup_eta` which is a timestamp like this: `2020-03-07T21:00:23.758Z `
- we want to calculate the time left in `MM:SS` from current time
- updated at every second, Eg. `setTimeInterval`, it should be counting down to 0
- only start counting down and update interval when there's less than 10 minutes left until `pickup_eta`, otherwise show the exact time string: "Pickup ETA: 17:47" or "Pickup ETA: 05:47 PM"
- only the component should be in the file called `CountDownTimer.js`
- when it's less than 5 minutes, styled the text bold red
- when the time is 0, stop the interval, and change the text to "DUE NOW"

Let me know if you have any questions. I would try searching online first for some examples of Countdown timers in React.js and then tweak it.

If you can finished this component, I also have other tasks that I can split out in chunk sizes to work on.

**Comment by Geno117** [comment]
Yea I'll try this out get back to you soon.

**Comment by Geno117** [comment]
by time stamp, do you mean a Date() object?

**Comment by zshanhui** [comment]
By timestamp, I mean exactly like this: `2020-03-07T21:00:23.758Z`

It comes from PostgreSQL. You can use `date-fns` which we already have in `package.json`

**Comment by Geno117** [comment]
I'll make some changes to use date-fns

**Comment by Geno117** [comment]
Opened a new request with a fully useable CountDownTimer. #30 
This request can be closed

**Pull request closed without merging**
